version: "3.5"

services:
    
    # this gives you a CLI to interrogate
    haxor:
      image: kalilinux/kali-rolling
      tty: true
      networks:
           - pakemon
      ports:
           - 55551:55553

    bettercap:
        image: bettercap/bettercap
        tty: true
        stdin_open: true
        networks:
            - pakemon
        ports:
            - 8080:8080
            - 8081:8081
        volumes:
            - ./pakemon.cap:/app/pakemon.cap
        command: -caplet pakemon

    # these are targets:
    nowasp:
        image: citizenstig/nowasp
        hostname: nowasp
        networks:
            - pakemon
    
    webgoat:
        image: webgoat/webgoat-7.1
        hostname: webgoat
        networks:
            - pakemon
    
    dvwa:
        image: citizenstig/dvwa
        hostname: dvwa
        networks:
            - pakemon
    
    securityshepherd:
        image: ismisepaul/securityshepherd
        hostname: securityshepherd
        networks:
            - pakemon

    vaas-cve-2014-0160:
        image: hmlio/vaas-cve-2014-0160
        hostname: vaas-cve-2014-0160
        networks:
            - pakemon
    cve-2017-7494:
        image: vulnerables/cve-2017-7494
        hostname: cve-2017-7494
        networks:
            - pakemon
    vaas-cve-2014-6271:
        image: hmlio/vaas-cve-2014-6271
        hostname: vaas-cve-2014-6271
        networks:
            - pakemon
   
    Host1:
        image: library/alpine
        hostname: Host1
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host2:
        image: library/alpine
        hostname: Host2
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host3:
        image: library/alpine
        hostname: Host3
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host4:
        image: library/alpine
        hostname: Host4
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host5:
        image: library/alpine
        hostname: Host5
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host6:
        image: library/alpine
        hostname: Host6
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host7:
        image: library/alpine
        hostname: Host7
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host8:
        image: library/alpine
        hostname: Host8
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host9:
        image: library/alpine
        hostname: Host9
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host10:
        image: library/alpine
        hostname: Host10
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host11:
        image: library/alpine
        hostname: Host11
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host12:
        image: library/alpine
        hostname: Host12
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host13:
        image: library/alpine
        hostname: Host13
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host14:
        image: library/alpine
        hostname: Host14
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host15:
        image: library/alpine
        hostname: Host15
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host16:
        image: library/alpine
        hostname: Host16
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host17:
        image: library/alpine
        hostname: Host17
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host18:
        image: library/alpine
        hostname: Host18
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host19:
        image: library/alpine
        hostname: Host19
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host20:
        image: library/alpine
        hostname: Host20
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host21:
        image: library/alpine
        hostname: Host21
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host22:
        image: library/alpine
        hostname: Host22
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host23:
        image: library/alpine
        hostname: Host23
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host24:
        image: library/alpine
        hostname: Host24
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host25:
        image: library/alpine
        hostname: Host25
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host26:
        image: library/alpine
        hostname: Host26
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host27:
        image: library/alpine
        hostname: Host27
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host28:
        image: library/alpine
        hostname: Host28
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host29:
        image: library/alpine
        hostname: Host29
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host30:
        image: library/alpine
        hostname: Host30
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host31:
        image: library/alpine
        hostname: Host31
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host32:
        image: library/alpine
        hostname: Host32
        tty: true 
        stdin_open: true 
        networks:
            - pakemon
    Host33:
        image: library/alpine
        hostname: Host33
        tty: true 
        stdin_open: true 
        networks:
            - pakemon



# careful, this is a war-zone :)
networks:
    pakemon:
        name: pakemon
